version: "3"
services:
  master:
    image: hadoopnhom17
    container_name: master
    hostname: master
    ports:
      - "9870:9870"   # HDFS UI
      - "8089:8088"   # YARN UI (đổi sang 8089 để tránh trùng 8088 của Superset bên trong)
      - "10001:10001" # Spark Thrift Server cho Superset
      - "7077:7077"   # Spark Master
    volumes:
      - ./data:/data:ro
      - ./src:/app/src:rw
    networks:
      - hadoop_net
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - HADOOP_HOME=/opt/hadoop
      - SPARK_HOME=/opt/spark
      - HIVE_HOME=/opt/hive

  slave1:
    image: hadoopnhom17
    container_name: slave1
    hostname: slave1
    networks:
      - hadoop_net

  slave2:
    image: hadoopnhom17
    container_name: slave2
    hostname: slave2
    networks:
      - hadoop_net

  # Superset - BI Tool
  superset:
    image: apache/superset:latest
    container_name: superset
    user: "root"
    ports:
      - "8080:8088"
    networks:
      - hadoop_net
    environment:
      - SUPERSET_SECRET_KEY=althea_lakehouse_2026
    entrypoint: >
      sh -c "
        pip install pyhive thrift thrift-sasl &&
        /usr/bin/run-server.sh
      "
    depends_on:
      - master

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    hostname: airflow-scheduler
    ports:
      - "8793:8793"
    volumes:
      - ./src:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
      - ./airflow_config:/opt/airflow/config
    networks:
      - hadoop_net
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    entrypoint: >
      sh -c "
        airflow db init &&
        airflow users create --role Admin --username admin --email admin@olist.com --firstname Admin --lastname User --password admin &&
        airflow scheduler
      "
    depends_on:
      - master

  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    hostname: airflow-webserver
    ports:
      - "8081:8080"
    volumes:
      - ./src:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
      - ./airflow_config:/opt/airflow/config
    networks:
      - hadoop_net
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    command: airflow webserver --port 8080
    depends_on:
      - airflow-scheduler

networks:
  hadoop_net:
    driver: bridge
