spark.sql.catalogImplementation            hive
spark.sql.warehouse.dir                    hdfs://master:9000/user/hive/warehouse
spark.hadoop.fs.defaultFS                  hdfs://master:9000
spark.hadoop.hive.metastore.uris           thrift://master:9083
spark.sql.sources.partitionOverwriteMode   dynamic
spark.sql.legacy.timeParserPolicy          LEGACY
